### ISSUE TITLE
[Bug] WebUI preloading entire page list

### ISSUE THREAD

**Issue by Secozzi** [Suwayomi/Suwayomi-WebUI#719] opened 2024-04-09 11:06 UTC
## Device information
- Suwayomi-WebUI version: Preview r1501
- Suwayomi-Server version: Preview v1.0.0-r1514-linux-x64
- Server Operating System: EndeavourOS Linux x86_64 6.8.2-arch2-1
- Server Desktop Environment: Plasma 6.0.3
- Server JVM version: bundled (openjdk version "1.8.0_392")
- Client Operating System:  Same as above
- Client Web Browser: LibreWolf 122.0.1-2

## Steps to reproduce
1. Click on a chapter

### Expected behavior
Only a set number of images should be preloaded

### Actual behavior
The entire list gets preloaded, and the client will load the images again when scrolled into view. (The server doesn't load the images twice)

**Comment by schroda** [comment] 2024-04-09 11:40
what do you mean by `the client will load the images again when scrolled into view`?
are they actually getting requested again from the server or are they loaded from the cache?

**Comment by Secozzi** [comment] 2024-04-09 11:44
According to devtools, they're requested twice. Once when the entire list gets preloaded, then again when the page is scrolled into view

**Comment by schroda** [comment] 2024-04-09 11:58
are they requested twice because they show up twice in the devtools or are they requested twice because the second request was actually fulfilled by the server instead being served from the cache?

because it works as intended for me - if the first request was successful the second request will just get served from the cache, as can be seen in the "Fulfilled by" column of the request

**Comment by Secozzi** [comment] 2024-04-09 12:21
The second request appears to be request twice, the transferred column doesn't mention anything about cache, and when scrolling into view there's a loading circle before the page is loaded.

**Comment by schroda** [comment] 2024-04-09 17:28
I can't reproduce this, please provide a screenshot from the network tab where this is the case

**Comment by Secozzi** [comment] 2024-04-09 19:35
https://github.com/Suwayomi/Suwayomi-WebUI/assets/49240133/f1a3e6cf-f683-41ff-b462-b6d7bc1012d9

**Comment by schroda** [comment] 2024-04-09 20:02
this is caused by the service worker that is registered, which the webUI does not provide itself, I assume you served VUI at some point via the server

you have to remove the server worker for it to work properly, go to the application tab > serverice worker and unregister it

**Comment by Secozzi** [comment] 2024-04-09 20:28
Ah, after unregistering that the images are being cached correctly.

On another note, it still tries to preload the entire list of pages, and if i understood https://github.com/Suwayomi/Suwayomi-WebUI/issues/662#issuecomment-2010155444 correctly it should only preload a set number of images

**Comment by schroda** [comment] 2024-04-09 21:01
there is currently no lazy loading for preloading pages

it will just request all pages, but only 5 images will be requested in parallel, so in case the reader gets left or the chapter gets changed, all queued/running image requests get canceled

so for preloading only n pages ahead, a feature request should be opened

**Comment by schroda** [comment] 2024-04-09 21:49
with #722 the service worker gets unregistered now, so this should not happen anymore and the server should not get spammed with image requests

I'll close this bug issue with #722 being integrated, as mentioned for the "preloading only n pages ahead" functionality, please create a feature request

**Closed by schroda** 2024-04-09 21:49 UTC
Labels: bug

**Comment by Secozzi** [comment] 2024-04-09 22:05
I see, thanks for the clarification
