### ISSUE TITLE
[Bug] "Show number of items" isn't working properly.

### ISSUE THREAD

**Issue by aryanpanwar07** [Suwayomi/Suwayomi-WebUI#570] opened 2024-01-25 20:20 UTC
![Screenshot 2024-01-26 014352](https://github.com/Suwayomi/Suwayomi-WebUI/assets/115069197/7b2e8eec-9786-4770-87d2-9259a1a927ac)

Whenever I remove any series from the category, count doesn't go down but when I add any series, it goes up.

**Comment by schroda** [comment] 2024-01-25 20:27
this is not a bug

when removing manga from the library they are not being removed from their categories
the number that is being displayed here is the number of manga in each category, thus, it includes manga that are not in the library
I'm also not going to change the logic, because working around the servers behaviour will just complecate the code

I can add a setting to remove manga from their categories when removing them from the library

in the meantime, there  is a option in the library settings to clean up the database by removing non library manga from categories

**Comment by aryanpanwar07** [comment] 2024-01-26 20:27
> this is not a bug
> 
> when removing manga from the library they are not being removed from their categories the number that is being displayed here is the number of manga in each category, thus, it includes manga that are not in the library I'm also not going to change the logic, because working around the servers behaviour will just complecate the code
> 
> I can add a setting to remove manga from their categories when removing them from the library
> 
> in the meantime, there is a option in the library settings to clean up the database by removing non library manga from categories

I've tried it but it doesn't change the count.
![Screenshot 2024-01-27 015614](https://github.com/Suwayomi/Suwayomi-WebUI/assets/115069197/ef8eddd2-22ba-4a4c-8910-9ad25a5d07f6)
![Screenshot 2024-01-27 015636](https://github.com/Suwayomi/Suwayomi-WebUI/assets/115069197/cc82384d-9d62-4e77-ac24-e47df5479cf4)

**Comment by schroda** [comment] 2024-01-26 20:38
ups, that actually did nothing, fixed in the latest preview version

**Closed** 2024-03-02 14:28 UTC
Labels: bug

**Comment by Hash6232** [comment] 2025-07-20 13:58
> I can add a setting to remove manga from their categories when removing them from the library

Any update on this?
